[[language]]
name = "unison"
language-servers = ["ucm"]

[language-server.ucm]
command = "ncat"
args = ["localhost", "5757"]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

# ------- svelte -----------
[language-server.svelteserver.config.configuration.typescript]
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true
inlayHints.parameterNames.enabled = "all"

[language-server.svelteserver.config.configuration.javascript]
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true
inlayHints.parameterNames.enabled = "all"


[[language]]
name = "svelte"
roots = ["package.json"]
language-servers = ["svelteserver"]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-language-server" ]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-language-server", "emmet-ls" ]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-language-server" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-language-server" ]

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

