[[language]]
name = "unison"
language-servers = ["ucm"]

[language-server.ucm]
command = "ncat"
args = ["localhost", "5757"]

[language-server.tailwindcss-language-server]
command = "tailwindcss-language-server"
args = ["--stdio"]

# Elixir using NextLS
[[language]]
name = "elixir"
scope = "source.elixir"
language-servers = ["nextls"]

[language-server.nextls]
command = "nextls"
args = ["--stdio=true"]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-language-server" ]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-language-server", "emmet-ls" ]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-language-server" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-language-server" ]
formatter = { command = "prettier" }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = ""}, environment = "node"}

[[language]]
name = "astro"
language-servers = [ "astro-ls" ]
